### ISSUE TITLE
Option to use az bicep instead of bicep.exe

### ISSUE THREAD

**Issue by mikanygTC** [sam-cogan/arm-ttk-extension-xplatform#13]
Currently bicep.exe is downloaded (if not present on agent) when analyzing bicep templates.

I would like the option to instead use az bicep which could be available on the agent through the azure cli. This would allow me to control bicep updates using az bicep upgrade in my pipelines and be sure that whatever tasks runs before and after ARM-TTK xplat tasks use same version of bicep as the ARM-TTK task.

It could be a simple flag under advanced, similiar to usePsCore with a default value of false, but if set to true, then calls to bicep.exe is replaced with az bicep.

If would be up to pipeline developer to ensure Azure CLI is installed prior to running the ARM-TTK task.

**Comment by sam-cogan** [comment]
Thanks for the suggestion @mikanygTC, this is a good idea, I'll look at adding it in.

**Comment by sam-cogan** [comment]
This has been added, there is now a useAzBicep flag that can be set to true to use the Az bicep command. This requires the azure cli to be installed and the ```az bicep install``` command to be run prior to running the extension.

**Comment by mikanygTC** [comment]
I can confirm it working as expected, great work 🥇
