### ISSUE TITLE
Support Pass/Fail/Other in NUnit XML result files

### ISSUE THREAD

**Issue by andrewholler** [sam-cogan/arm-ttk-extension-xplatform#18]
If you run from PowerShell and from the pipeline, PowerShell will return a "recommended" or "warning" result while the extension will mark it as passed. Can we differentiate those in the test result files?

![image](https://user-images.githubusercontent.com/17442804/126382306-a67597c1-8cb2-43ca-be07-0deb6fde9f5c.png)

**Comment by sam-cogan** [comment]
I've been looking into this issue recently (sorry it took a while), but unfortunately it seems that the schema for reading the test data in Azure DevOps doesn't really support a warning state. It can support pass, fail or other. We could use "other" for warnings, however, it also doesn't provide any facilities to display the warning message. The only state that allows for providing a message is "failed". So unfortunately I don't think this is feasible.
