### ISSUE TITLE
Incorrect help link for XPlat task v1.2.0 which doesn't appear to exist in the releases here?

### ISSUE THREAD

**Issue by spoelstraethan** [sam-cogan/arm-ttk-extension-xplatform#21]
```
Starting: Run ARM TTK Tests XPlat
==============================================================================
Task         : Run Azure RM TTK Tests (Cross Platform)
Description  : Run Azure Resource Manager Template Test Kit Tests against ARM & Bicep Templates
Version      : 1.2.0
Author       : Sam Cogan
Help         : [More Information](https://github.com/sam-cogan/arm-ttk-extension/blob/master/README.md)
==============================================================================
Using executable 'pwsh'
```

**Comment by sam-cogan** [comment]
Thanks for spotting that, a new release is going out now that fixes this.

**Comment by spoelstraethan** [comment]
In addition to the incorrect help link, it appears the task version never gets updated even though you are changing the package version in the `vss-extension.json` and some other metadata in the `task.json`.

It might make it harder for people to report bugs against a specific version if the task always displays a static incorrect version.

The major/minor/patch here
https://github.com/sam-cogan/arm-ttk-extension-xplatform/blob/c38903bd59a74def01cc0a66b8addf2a3290b6f9/arm-ttk-extension-xplatform/task.json#L12C8-L16

could maybe be updated by another invocation of this task or some additional find/replace parameters?
https://github.com/sam-cogan/arm-ttk-extension-xplatform/blob/c38903bd59a74def01cc0a66b8addf2a3290b6f9/.github/workflows/build-extension.yml#L50

**Comment by sam-cogan** [comment]
The task version does get updated, but it is manual task currently, and where there is just a docs change I didn't updated it.
