### ISSUE TITLE
Run Azure RM TTK Tests (Cross Platform)' version 1 (RunARMTTKTestsXPlat@1) is dependent on a Node version (10) that is end-of-life. 

### ISSUE THREAD

**Issue by MarkParsonsOS** [sam-cogan/arm-ttk-extension-xplatform#32]
We are now getting the following warning when running a pipeline: 
##[warning]Task 'Run Azure RM TTK Tests (Cross Platform)' version 1 (RunARMTTKTestsXPlat@1) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance

**Comment by sam-cogan** [comment]
Thanks for pointing this out, I'll get that updated.
