### ISSUE TITLE
Bump to arm-ttk v0.25

### ISSUE THREAD

**Issue by D-Bissell** [sam-cogan/arm-ttk-extension-xplatform#33]
Could you please bump to arm-ttk v0.25.
I'm getting some types not available errors which im assuming is the older ttk versions not knowing about newer API versions

```Warning BCP081: Resource type "Microsoft.Network/networkSecurityGroups@2024-03-01" does not have types available.```

**Comment by sam-cogan** [comment]
I'll update the version shortly, however I'm dubious this will fix your issue. That error message usually means that the resource provider (in this case networking) hasn't published the schema for that API version. You'd get the same warning in VS Code as well.

**Comment by D-Bissell** [comment]
> I'll update the version shortly, however I'm dubious this will fix your issue. That error message usually means that the resource provider (in this case networking) hasn't published the schema for that API version. You'd get the same warning in VS Code as well.

Thanks.  I'm not getting the error in vscode, the intellisense works fine with the 2024-03-01 API.

For the moment I've changed all the resources using Microsoft.Network API down to 2024-01-01.  I'll try bumping them up again on Monday.

**Comment by D-Bissell** [comment]
Sorry for the dumb question but how to I update the extension?  I still have the previous version in my DevOps org but cant find a way to make it update.

**Comment by sam-cogan** [comment]
The extension updates automatically, however there was an issue with the release pipeline so the changes hadn't actually gone in. This has just completed, so your extension should update in the next 30 mins or so.

**Comment by D-Bissell** [comment]
Got it, thanks.  You were right though, it has not helped with the API schema warnings.
