### ISSUE TITLE
Linter suppress rules not evaluated

### ISSUE THREAD

**Issue by tnsholding** [sam-cogan/arm-ttk-extension-xplatform#9]
Starting to use the new cross platform version.

In the 'old' version bicep linter suppres rules seemed to be evaluated, i.e. 

```
#disable-next-line secure-secrets-in-params
param SomeParamWithSecretInName string 
```

But now this does not seem to be evaluated any longer? - getting error 
`Parameter "SomeParamWithSecretInName" is of type "string" but should be secure. in template file main.json`

even though there is a suppress statement above.

**Comment by sam-cogan** [comment]
Have you run the latest version of the TTK manually against this file at all? I aks because the supression logic is entirely in the TTK, not the extension. I'll see if I can replicate when I get a minute.

**Comment by sam-cogan** [comment]
I'm not currently able to replicate this, could you paste your test results here for me to have a close look please?

**Comment by spoelstraethan** [comment]
@tnsholding are you running the TTK XPlat with `usePSCore: true` or just copying the params from the previous TTK extension?

**Comment by sam-cogan** [comment]
Closing due to lack of response.
